services:
  - type: web
    name: jonathans-jots
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: jonathans-jots-db
          property: internalConnectionString
      - key: VITE_APP_TITLE
        value: Jonathan's Jots
      - key: VITE_OAUTH_PORTAL_URL
        value: https://jonathans-jots.onrender.com
      - key: VITE_APP_ID
        value: jonathans-jots
databases:
  - name: jonathans-jots-db
    plan: free

